### ISSUE TITLE
新增文章里面，上传封面接口报错

### ISSUE THREAD

**Issue by nlbss** [wmy94827/nest-react-blog#2]
![image](https://user-images.githubusercontent.com/23022044/169971935-673418c3-c95f-41e5-b59f-d0cab3408a1a.png)

**Comment by wmy94827** [comment]
> ![image](https://user-images.githubusercontent.com/23022044/169971935-673418c3-c95f-41e5-b59f-d0cab3408a1a.png)



> ![image](https://user-images.githubusercontent.com/23022044/169971935-673418c3-c95f-41e5-b59f-d0cab3408a1a.png)

已经处理好了~
